package com.movieexplorer.core.di

import android.content.Context
import androidx.room.Room
import com.movieexplorer.home_screen.data.local.MovieDatabase
import com.movieexplorer.home_screen.data.local.MovieDao
import com.movieexplorer.watchlist_screen.data.local.WatchlistDao
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import javax.inject.Singleton

@Module //This class provides dependencies like a factory class
@InstallIn(SingletonComponent::class) // This module lives for the entire app lifetime So the database will be created once only
object DatabaseModule {

    @Provides // this tell hilt This function creates an object
    @Singleton //ONLY ONE database instance in the entire app
    fun provideMovieDatabase(
        @ApplicationContext context: Context
    ): MovieDatabase {
        return Room.databaseBuilder( //This creates the actual SQLite database
            context, //Used to access device storage
            MovieDatabase::class.java, //Use this schema definition
            "movie_database" //This is the file name stored on the device
        )   .fallbackToDestructiveMigration()
            .build() //This actually creates the database instance without it nothing created
    }

    @Provides //I already know how to create MovieDatabase, so I will use it here, Hilt → creates MovieDatabase → then creates MovieDao
    fun provideMovieDao(
        database: MovieDatabase
    ): MovieDao {
        return database.movieDao()
    }

    @Provides
    fun provideWatchlistDao(
        database: MovieDatabase
    ): WatchlistDao {
        return database.watchlistDao()
    }
}
/*
Why SingletonComponent?

Because Room database:

is expensive to create
should NOT be recreated multiple times
must stay consistent across the app
---------
we never do
MovieDao()

Because:

DAO is generated by Room
it depends on the database instance
Room controls lifecycle internally
 */